### ISSUE TITLE
stdout maxBuffer exceeded

### ISSUE THREAD

**Issue by RichardLitt** [IonicaBizau/git-unsaved#4]
```sh
10:09 ~/src 🐕  git-unsaved
stdout maxBuffer exceeded
```

I am not sure why this is happening. Too many local repos to check?

**Comment by IonicaBizau** [comment]
Hmm, I guess at least one of them has a huge output of `git status`...

**Comment by RichardLitt** [comment]
It's hard to see which one it is, as I have around 100 repositories in that folder. Is there a debug option so that I can see which repository it is getting stuck on? 

Btw - thanks. This is an awesome tool.

**Comment by IonicaBizau** [comment]
Try doing this:

```sh
$ git clone https://github.com/IonicaBizau/git-unsaved.git
$ cd git-unsaved
$ npm i
```

Instead of [`cb(err)`](https://github.com/IonicaBizau/git-unsaved/blob/494c276072fbab58e81597a3801a437880c9a880/lib/index.js#L29) you can do ``` cb(`There was a problem checking ${repoPath}: ${err.message}`) ```

Then in another terminal instance, `cd ../path/to/your/repos/folder` and run `git-unsaved`.

The real problem comes from [`git-state`](https://github.com/watson/git-state). After a quick check, by replacing `spawn = require("child_process").spawn` with `spawn = require("spawno")`, I'd expect that to work (because [`spawno`](https://github.com/IonicaBizau/spawno) expands the output size).

Hope that helps! 😄 Contributions are more than welcome!

**Comment by RichardLitt** [comment]
Thanks. That helped. PR submitted with fix!

**Comment by IonicaBizau** [comment]
@RichardLitt Thanks for that! ❇️

**Comment by IonicaBizau** [comment]
#5 added the repo path in the error output, however this issue must be addressed in the `git-state` library.

/cc @watson Can you please take a look?

**Comment by watson** [comment]
@IonicaBizau What did you want me to look at? If you need changes to git-state, you are welcome to submit a PR 😃

**Comment by IonicaBizau** [comment]
@watson OK, I opened an issue there. 😁

**Comment by watson** [comment]
I've added the ability to specify a custom `maxBuffer` in version 4 of git-state which have just been published to npm

**Comment by IonicaBizau** [comment]
@watson That was fast! Thanks!
Sorry if I'm missing anything, is the `git-state@4.x.x` published to npm?

**Comment by IonicaBizau** [comment]
Oh yes, I did `npm i -S git-state` instead of `npm i -S git-state@latest` 😁
